<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-01-16 16:52:56",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "7428308b8b340602872bbc4e67c8d654",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-01-16 16:51:56",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "f9030910c77ee4002ce208c1008efbba",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2020-01-16 16:50:56",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "219d25578a311ce1c4907e2486402dbb",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2020-01-16 16:49:56",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "d8063b1d20fb0ed8e1d116e942ff913e",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}